
add_requires("glfw","glbinding","glm","glad")
add_requires("imgui",{configs={ glfw_opengl3=true }})
target("ui")
    set_kind("static")
    add_files("*.cc")
    add_rules("opengl")
    add_packages("glfw","imgui")
    add_packages("glm",{public=true})
    add_deps("libxc","event","ecs","xcmath","xcal","xcal-opengl-render")
    add_includedirs("../",{public=true})
    add_includedirs("../common",{public=true})
