
add_requires("glfw","glbinding","glm")
add_requires("imgui",{configs={ glfw_opengl3=true }})
target("ui")
    set_kind("static")
    add_files("*.cc")
    add_packages("glfw","imgui","glbinding")
    add_packages("glm",{public=true})
    add_defines("USE_GLBINDING")
    add_deps("libxc","event","ecs","xcmath","xcal")
    add_includedirs("../",{public=true})
    add_includedirs("../common",{public=true})
