includes("events")
includes("camera")
includes("transform")
includes("object")

target("xcal2")
    set_kind("phony")
    add_deps( "xcal-events")
    add_deps( "xcal-camera")
    add_deps( "xcal-transform")
    add_deps( "xcal-object")
