target("ex-glfw")
    set_kind("binary")
    add_files("*.cc")
    add_deps("ecs", "xc-glfw-support","xc-opengl-support")
    add_deps("xcal-transform","xcal-camera","xcal-camera-ui-controler")
    add_defines("USE_GLBINDING")
